### ISSUE TITLE
when you will add service provider and orm ?

### ISSUE THREAD

**Issue by mtariqsajid** [amirfaramarzi/tower#8]
this framework is very awesome and very fast. when you are going to add orm that support mysql and mongo DB and service provider ?

**Comment by amirfaramarzi** [comment]
Hello Tariq

Thank you very much

Currently we are using laravel package to communicate with mysql, but because laravel's orm is very slow, we have not activated it at the moment, but we are building a dedicated orm so that we can increase the speed in this part as well, but Unfortunately, there is no specific time to complete this orm

Regarding mongodb, I have to say that we haven't reviewed it yet, but you can use the packages made by other people to communicate with mongo.

**Comment by n0nag0n** [comment]
@amirfaramarzi I created the [Flight Active Record ORM](https://github.com/flightphp/active-record). Is it a possibility for you to just make a few tweaks with connection pooling and just use that class to save you some time?

**Comment by amirfaramarzi** [comment]
hi @n0nag0n,

Unfortunately, it is currently not possible to add "Flight Active Record ORM" to Fomo, as security and performance tests need to be conducted.
However, you can use "Flight Active Record ORM" in your projects by creating your own service through the use of Services.
